leagues_raw = {'/premier-league/gesamtspielplan/wettbewerb/GB1/saison_id/2022': 'Wielka Brytania',
           '/laliga/gesamtspielplan/wettbewerb/ES1/saison_id/2022': 'Europa Południowa',
           '/uefa-champions-league/gesamtspielplan/pokalwettbewerb/CL/saison_id/2022': 'Liga Mistrzów',
           '/europa-league/gesamtspielplan/pokalwettbewerb/EL/saison_id/2022': 'Liga Europy',
           '/uefa-europa-conference-league/gesamtspielplan/pokalwettbewerb/UCOL/saison_id/2022': 'Liga Konferencji Europy',
           '/3-liga-grupa-iii/gesamtspielplan/wettbewerb/PL33/saison_id/2022': 'Rozgrywki Polskiego Związku Piłki Nożnej',
           '/3-liga-grupa-ii/gesamtspielplan/wettbewerb/PL32/saison_id/2022': 'Rozgrywki Polskiego Związku Piłki Nożnej',
           '/3-liga-grupa-iv/gesamtspielplan/wettbewerb/PL34/saison_id/2022': 'Rozgrywki Polskiego Związku Piłki Nożnej',
           '/3-liga-grupa-i/gesamtspielplan/wettbewerb/PL31/saison_id/2022': 'Rozgrywki Polskiego Związku Piłki Nożnej',
           '/ewinner-2-liga/gesamtspielplan/wettbewerb/PL2L/saison_id/2022': 'Rozgrywki Polskiego Związku Piłki Nożnej',
           '/fortuna-1-liga/gesamtspielplan/wettbewerb/PL2/saison_id/2022': 'Rozgrywki Polskiego Związku Piłki Nożnej',
           '/2-bundesliga/gesamtspielplan/wettbewerb/L2/saison_id/2022': 'Europa Zachodnia',
           '/ligue-2/gesamtspielplan/wettbewerb/FR2/saison_id/2022': 'Europa Zachodnia',
           '/laliga2/gesamtspielplan/wettbewerb/ES2/saison_id/2022': 'Europa Południowa',
           '/serie-b/gesamtspielplan/wettbewerb/IT2/saison_id/2022': 'Europa Południowa',
           '/championship/gesamtspielplan/wettbewerb/GB2/saison_id/2022': 'Wielka Brytania',
           '/cymru-premier/gesamtspielplan/wettbewerb/WAL1/saison_id/2022': 'Wielka Brytania',
           '/besta-deild/gesamtspielplan/wettbewerb/IS1/saison_id/2022': 'Europa Zachodnia',
           '/league-of-ireland-premier-division/gesamtspielplan/wettbewerb/IR1/saison_id/2022': 'Wielka Brytania',
           '/fortuna-liga-relegation-group/gesamtspielplan/wettbewerb/SLMR/saison_id/2022': 'Reszta Europy',
           '/meridianbet-1-cfl/gesamtspielplan/wettbewerb/MNE1/saison_id/2022': 'Reszta Europy',
           '/danske-bank-premiership/gesamtspielplan/wettbewerb/NIR1/saison_id/2022': 'Wielka Brytania',
           '/fortuna-liga-championship-group/gesamtspielplan/wettbewerb/SLAR/saison_id/2022': 'Reszta Europy',
           '/wyszejszaja-liha/gesamtspielplan/wettbewerb/WER1/saison_id/2022': 'Reszta Europy',
           '/prva-liga/gesamtspielplan/wettbewerb/SL1/saison_id/2022': 'Reszta Europy',
           '/premyer-liqa/gesamtspielplan/wettbewerb/AZ1/saison_id/2022': 'Reszta Europy',
           '/fortuna-liga/gesamtspielplan/wettbewerb/SLO1/saison_id/2022': 'Reszta Europy',
           '/premier-liga/gesamtspielplan/wettbewerb/KAS1/saison_id/2022': 'Reszta Europy',
           '/nemzeti-bajnoksag/gesamtspielplan/wettbewerb/UNG1/saison_id/2022': 'Reszta Europy',
           '/ligat-haal/gesamtspielplan/wettbewerb/ISR1/saison_id/2022': 'Reszta Europy',
           '/efbet-liga/gesamtspielplan/wettbewerb/BU1/saison_id/2022': 'Reszta Europy',
           '/protathlima-cyta/gesamtspielplan/wettbewerb/ZYP1/saison_id/2022': 'Europa Południowa',
           '/eliteserien/gesamtspielplan/wettbewerb/NO1/saison_id/2022': 'Europa Zachodnia',
           '/allsvenskan/gesamtspielplan/wettbewerb/SE1/saison_id/2022': 'Europa Zachodnia',
           '/superliga/gesamtspielplan/wettbewerb/RO1/saison_id/2022': 'Reszta Europy',
           '/fortuna-liga/gesamtspielplan/wettbewerb/TS1/saison_id/2022': 'Reszta Europy',
           '/super-liga-srbije/gesamtspielplan/wettbewerb/SER1/saison_id/2022': 'Reszta Europy',
           '/supersport-hnl/gesamtspielplan/wettbewerb/KR1/saison_id/2022': 'Reszta Europy',
           '/superligaen/gesamtspielplan/wettbewerb/DK1/saison_id/2022': 'Europa Zachodnia',
           '/pko-ekstraklasa/gesamtspielplan/wettbewerb/PL1/saison_id/2022': 'Ekstraklasa',
           '/super-league/gesamtspielplan/wettbewerb/C1/saison_id/2022': 'Europa Zachodnia',
           '/premier-liha/gesamtspielplan/wettbewerb/UKR1/saison_id/2022': 'Reszta Europy',
           '/scottish-premiership/gesamtspielplan/wettbewerb/SC1/saison_id/2022': 'Wielka Brytania',
           '/super-league-1/gesamtspielplan/wettbewerb/GR1/saison_id/2022': 'Europa Południowa',
           '/bundesliga/gesamtspielplan/wettbewerb/A1/saison_id/2022': 'Europa Zachodnia',
           '/premier-liga/gesamtspielplan/wettbewerb/RU1/saison_id/2022': 'Reszta Europy',
           '/jupiler-pro-league/gesamtspielplan/wettbewerb/BE1/saison_id/2022': 'Europa Zachodnia',
           '/super-lig/gesamtspielplan/wettbewerb/TR1/saison_id/2022': 'Europa Południowa',
           '/eredivisie/gesamtspielplan/wettbewerb/NL1/saison_id/2022': 'Europa Zachodnia',
           '/liga-portugal/gesamtspielplan/wettbewerb/PO1/saison_id/2022': 'Europa Południowa',
           '/ligue-1/gesamtspielplan/wettbewerb/FR1/saison_id/2022': 'Europa Zachodnia',
           '/bundesliga/gesamtspielplan/wettbewerb/L1/saison_id/2022': 'Europa Zachodnia',
           'https://www.transfermarkt.pl/serie-a/gesamtspielplan/wettbewerb/IT1/saison_id/2022': 'Europa Południowa'}


leagues = {key.split('/')[4]: value for key, value in leagues_raw.items()}
