leagues_raw = {'/premier-league/gesamtspielplan/wettbewerb/GB1/saison_id/2022': 'Wielka Brytania',
           '/laliga/gesamtspielplan/wettbewerb/ES1/saison_id/2022': 'Europa Południowa',
           '/uefa-champions-league/gesamtspielplan/pokalwettbewerb/CL/saison_id/2022': 'Liga Mistrzów',
           '/europa-league/gesamtspielplan/pokalwettbewerb/EL/saison_id/2022': 'Liga Europy',
           '/uefa-europa-conference-league/gesamtspielplan/pokalwettbewerb/UCOL/saison_id/2022': 'Liga Konferencji Europy',
           '/3-liga-grupa-iii/gesamtspielplan/wettbewerb/PL33/saison_id/2022': 'Rozgrywki Polskiego Związku Piłki Nożnej',
           '/3-liga-grupa-ii/gesamtspielplan/wettbewerb/PL32/saison_id/2022': 'Rozgrywki Polskiego Związku Piłki Nożnej',
           '/3-liga-grupa-iv/gesamtspielplan/wettbewerb/PL34/saison_id/2022': 'Rozgrywki Polskiego Związku Piłki Nożnej',
           '/3-liga-grupa-i/gesamtspielplan/wettbewerb/PL31/saison_id/2022': 'Rozgrywki Polskiego Związku Piłki Nożnej',
           '/ewinner-2-liga/gesamtspielplan/wettbewerb/PL2L/saison_id/2022': 'Rozgrywki Polskiego Związku Piłki Nożnej',
           '/fortuna-1-liga/gesamtspielplan/wettbewerb/PL2/saison_id/2022': 'Rozgrywki Polskiego Związku Piłki Nożnej',
           '/2-bundesliga/gesamtspielplan/wettbewerb/L2/saison_id/2022': 'Europa Zachodnia',
           '/ligue-2/gesamtspielplan/wettbewerb/FR2/saison_id/2022': 'Europa Zachodnia',
           '/laliga2/gesamtspielplan/wettbewerb/ES2/saison_id/2022': 'Europa Południowa',
           '/serie-b/gesamtspielplan/wettbewerb/IT2/saison_id/2022': 'Europa Południowa',
           '/championship/gesamtspielplan/wettbewerb/GB2/saison_id/2022': 'Wielka Brytania',
           '/cymru-premier/gesamtspielplan/wettbewerb/WAL1/saison_id/2022': 'Wielka Brytania',
           '/besta-deild/gesamtspielplan/wettbewerb/IS1/saison_id/2022': 'Europa Zachodnia',
           '/league-of-ireland-premier-division/gesamtspielplan/wettbewerb/IR1/saison_id/2022': 'Wielka Brytania',
           '/fortuna-liga-relegation-group/gesamtspielplan/wettbewerb/SLMR/saison_id/2022': 'Europa Wschodnia',
           '/meridianbet-1-cfl/gesamtspielplan/wettbewerb/MNE1/saison_id/2022': 'Europa Wschodnia',
           '/danske-bank-premiership/gesamtspielplan/wettbewerb/NIR1/saison_id/2022': 'Wielka Brytania',
           '/fortuna-liga-championship-group/gesamtspielplan/wettbewerb/SLAR/saison_id/2022': 'Europa Wschodnia',
           '/wyszejszaja-liha/gesamtspielplan/wettbewerb/WER1/saison_id/2022': 'Europa Wschodnia',
           '/prva-liga/gesamtspielplan/wettbewerb/SL1/saison_id/2022': 'Europa Wschodnia',
           '/premyer-liqa/gesamtspielplan/wettbewerb/AZ1/saison_id/2022': 'Europa Wschodnia',
           '/fortuna-liga/gesamtspielplan/wettbewerb/SLO1/saison_id/2022': 'Europa Wschodnia',
           '/premier-liga/gesamtspielplan/wettbewerb/KAS1/saison_id/2022': 'Europa Wschodnia',
           '/nemzeti-bajnoksag/gesamtspielplan/wettbewerb/UNG1/saison_id/2022': 'Europa Wschodnia',
           '/ligat-haal/gesamtspielplan/wettbewerb/ISR1/saison_id/2022': 'Europa Wschodnia',
           '/efbet-liga/gesamtspielplan/wettbewerb/BU1/saison_id/2022': 'Europa Wschodnia',
           '/protathlima-cyta/gesamtspielplan/wettbewerb/ZYP1/saison_id/2022': 'Europa Południowa',
           '/eliteserien/gesamtspielplan/wettbewerb/NO1/saison_id/2022': 'Europa Zachodnia',
           '/allsvenskan/gesamtspielplan/wettbewerb/SE1/saison_id/2022': 'Europa Zachodnia',
           '/superliga/gesamtspielplan/wettbewerb/RO1/saison_id/2022': 'Europa Wschodnia',
           '/fortuna-liga/gesamtspielplan/wettbewerb/TS1/saison_id/2022': 'Europa Wschodnia',
           '/super-liga-srbije/gesamtspielplan/wettbewerb/SER1/saison_id/2022': 'Europa Wschodnia',
           '/supersport-hnl/gesamtspielplan/wettbewerb/KR1/saison_id/2022': 'Europa Wschodnia',
           '/superligaen/gesamtspielplan/wettbewerb/DK1/saison_id/2022': 'Europa Zachodnia',
           '/pko-ekstraklasa/gesamtspielplan/wettbewerb/PL1/saison_id/2022': 'Ekstraklasa',
           '/super-league/gesamtspielplan/wettbewerb/C1/saison_id/2022': 'Europa Zachodnia',
           '/premier-liha/gesamtspielplan/wettbewerb/UKR1/saison_id/2022': 'Europa Wschodnia',
           '/scottish-premiership/gesamtspielplan/wettbewerb/SC1/saison_id/2022': 'Wielka Brytania',
           '/super-league-1/gesamtspielplan/wettbewerb/GR1/saison_id/2022': 'Europa Południowa',
           '/bundesliga/gesamtspielplan/wettbewerb/A1/saison_id/2022': 'Europa Zachodnia',
           '/premier-liga/gesamtspielplan/wettbewerb/RU1/saison_id/2022': 'Europa Wschodnia',
           '/jupiler-pro-league/gesamtspielplan/wettbewerb/BE1/saison_id/2022': 'Europa Zachodnia',
           '/super-lig/gesamtspielplan/wettbewerb/TR1/saison_id/2022': 'Europa Południowa',
           '/eredivisie/gesamtspielplan/wettbewerb/NL1/saison_id/2022': 'Europa Zachodnia',
           '/liga-portugal/gesamtspielplan/wettbewerb/PO1/saison_id/2022': 'Europa Południowa',
           '/ligue-1/gesamtspielplan/wettbewerb/FR1/saison_id/2022': 'Europa Zachodnia',
           '/bundesliga/gesamtspielplan/wettbewerb/L1/saison_id/2022': 'Europa Zachodnia',
           '/serie-a/gesamtspielplan/wettbewerb/IT1/saison_id/2022': 'Europa Południowa',
           '/fa-cup/gesamtspielplan/pokalwettbewerb/FAC/saison_id/2022': 'Wielka Brytania',
           '/efl-cup/gesamtspielplan/pokalwettbewerb/CGB/saison_id/2022': 'Wielka Brytania',
           '/magyar-kupa/gesamtspielplan/pokalwettbewerb/UNGP/saison_id/2022': 'Europa Wschodnia',
           '/svenska-cupen/gesamtspielplan/pokalwettbewerb/SEC/saison_id/2022': 'Europa Zachodnia',
           '/hrvatski-nogometni-kup/gesamtspielplan/pokalwettbewerb/KRC/saison_id/2022': 'Europa Wschodnia',
           '/kup-srbije/gesamtspielplan/pokalwettbewerb/SERP/saison_id/2022': 'Europa Wschodnia',
           '/cupa-romaniei/gesamtspielplan/pokalwettbewerb/ROMP/saison_id/2022': 'Europa Wschodnia',
           '/sydbank-pokalen/gesamtspielplan/pokalwettbewerb/DKP/saison_id/2022': 'Europa Zachodnia',
           '/fortuna-polnischer-pokal/gesamtspielplan/pokalwettbewerb/POPU/saison_id/2022': 'Rozgrywki Polskiego Związku Piłki Nożnej',
           '/schweizer-cup/gesamtspielplan/pokalwettbewerb/SCC/saison_id/2022': 'Europa Zachodnia',
           '/sfa-cup/gesamtspielplan/pokalwettbewerb/SFA/saison_id/2022': 'Wielka Brytania',
           '/kypello-elladas/gesamtspielplan/pokalwettbewerb/GRP/saison_id/2022': 'Europa Południowa',
           '/beker-van-belgie/gesamtspielplan/pokalwettbewerb/CCB/saison_id/2022': 'Europa Zachodnia',
           '/russischer-pokal/gesamtspielplan/pokalwettbewerb/RUP/saison_id/2022': 'Europa Wschodnia',
           '/turkiye-kupasi/gesamtspielplan/pokalwettbewerb/TRP/saison_id/2022': 'Europa Południowa',
           '/toto-knvb-beker/gesamtspielplan/pokalwettbewerb/NLP/saison_id/2022': 'Europa Zachodnia',
           '/taca-de-portugal-placard/gesamtspielplan/pokalwettbewerb/POPO/saison_id/2022': 'Europa Południowa',
           '/coupe-de-france/gesamtspielplan/pokalwettbewerb/FRC/saison_id/2022': 'Europa Zachodnia',
           '/dfb-pokal/gesamtspielplan/pokalwettbewerb/DFB/saison_id/2022': 'Europa Zachodnia',
           '/coppa-italia/gesamtspielplan/pokalwettbewerb/CIT/saison_id/2022': 'Europa Południowa',
           '/copa-del-rey/gesamtspielplan/pokalwettbewerb/CDR/saison_id/2022': 'Europa Południowa'
           }


leagues = {key.split('/')[4]: value for key, value in leagues_raw.items()}
